name: Run FDAST Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-fdast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13' # Match the Python version used locally

    - name: Install dependencies
      run: |
        python -m venv polaris-env
        source polaris-env/bin/activate
        pip install requests

    - name: Run FDAST script
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
        PROJECT_NAME: ${{ vars.PROJECT_NAME }}
        NOTES: ${{ vars.NOTES }}
        API_TOKEN: ${{ secrets.API_TOKEN }} # Use GitHub Secrets for sensitive data
      run: |
        source polaris-env/bin/activate
        python fdast.py
